# All the executables to be generated
all: variables height calculator

# Instructions for compiling
variables: variables.cpp
	g++ variables.cpp -o variables 

height: height.cpp 
	g++ height.cpp -o height.cpp

calculator: calculator.cpp 
	g++ calculator.cpp -o calculator

# Instructions for cleaning
clean: 
	rm variables
	rm height 
	rm calculator